language: cpp
sudo: required
dist: trusty
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_PISTACHE_EXAMPLES=TRUE -DBUILD_PISTACHE_TESTS=TRUE .. 
  - make
compiler:
    - clang
    - gcc
branches:
    only:
        - master
