# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: centos:centos8
    steps:
      - run: dnf install -y git rpm-build cmake openssl-devel libcurl-devel gcc-c++ make
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: prepare
          command: |
            mkdir -p build
            cd build
            cmake ../
            make dist
            cd ../
            mkdir -p ~/rpmbuild/SOURCES
            mkdir -p ~/rpmbuild/SPECS
            cp build/libpistache.spec ~/rpmbuild/SPECS
            cp build/pistache*.tar.bz2 ~/rpmbuild/SOURCES/
      - run:
          name: build
          command: |
            echo "-j 4" > ~/build_opts
            cd ~/rpmbuild/SPECS
            rpmbuild -ba libpistache.spec
      - store_artifacts:
          path: /root/rpmbuild/RPMS/x86_64/
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  build:
    # Run the welcome/run job in its own container
    jobs:
      - build
